name: Autograder CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Upgrade pip
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pytest pylint
          fi

      # Step 5: Run tests with pytest
      - name: Run tests
        run: pytest -q

      # Step 6: Run pylint separately
      - name: Run pylint
        run: pylint app tests

      # Step 7: Show Python & pip info (optional)
      - name: Python and pip info
        run: |
          python --version
          pip --version
          python -m pip list --format=columns
